### PR TITLE
Adds datadog integration

### LINKED ISSUE #677: Setup datadog

### PR DESCRIPTION
**Pull request by whereismyjetpack**
Fixes #677 
Optionally configures DataDog APM. configures the DataDog gem via `config` module.

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
Before Merging I'd like to test this branch on QA if possible. The code shouldn't cause any issues either way, just want to be careful. 

Before a production deploy I will have to configure the agent on the production nodes, I plan on doing this *very soon now

**Comment by banukutlu** [comment]
> Before Merging I'd like to test this branch on QA if possible. The code shouldn't cause any issues either way, just want to be careful.
> 
> Before a production deploy I will have to configure the agent on the production nodes, I plan on doing this *very soon now

it sounds good to me, we can deploy the branch to QA.

**Comment by whereismyjetpack** [comment]
the production nodes are good to go. depends on https://github.com/psu-libraries/psulib_blacklight_deploy/pull/109

**Review by banukutlu — APPROVED** [review]
thanks @whereismyjetpack

**Pull request merged**
