### PR TITLE
Shakapacker migration

### LINKED ISSUE #1236: psulib_blacklight security vulnerabilities

### PR DESCRIPTION
**Pull request by Smullz622**
Fixes #1236 

migrating from web packer to shakapacker

Notes: getting jQuery to work was the biggest hurdle. Eventual solution was to move the logic that adds jQuery from `config/webpack/environment.js` to `config/webpack/webpack.config.js`

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
I'd feel better merging this if we had a preview to test first. I'll fork this branch and deploy so we can test that the asset compilation works in k8s

**Comment by Smullz622** [comment]
Sounds good, thanks @whereismyjetpack

**Comment by whereismyjetpack** [comment]
This looks good to me, https://catalog-shak.dev.k8s.libraries.psu.edu/

**Review by whereismyjetpack — DISMISSED** [review]

**Review by ajkiessl — COMMENTED** [review]
This is a bit picky, but there's a reference to webpacker in the README: "Because we use webpacker, when upgrading the Blacklight gem for this application, we should also update package.json to the same version as the installed gem so as to keep these things in step from Blacklight."

Otherwise, this looks good.

**Review by ajkiessl — APPROVED** [review]
:shipit:

**Pull request merged**
