### PR TITLE
Improve "Access Online" Links UI

### LINKED ISSUE #672: Review/revise link display to online content
Requires https://github.com/psu-libraries/psulib_traject/issues/277
- [x] Links to our digital collections should be cool and more prominent kind of like HathiTrust
- [x] Links to general online content should overall be more eye-catching and grab the user better.

### PR DESCRIPTION
**Pull request by nicktiberi**
Re: #672

- Calls more attention to online resources by putting them in a callout box.
- Visually distinguishes resources in the Penn State Digital Collections from other external online resources.

**External Online Resource:**
Screen Shot 2021-03-11 at 9 11 58 AM

**Penn State Digital Collections Resource:**
Screen Shot 2021-03-11 at 9 22 22 AM

### CODE REVIEW

**Comment by banukutlu** [comment]
@nicktiberi Would you pls rebase this branch to get the Github Actions fix from main so the checks would run for this PR? thanks!

**Comment by nicktiberi** [comment]
@banukutlu - this should be ready for review! 

@awead helped me clean this up this afternoon. The thumbnail is now linking properly on the index view now that we are using the `Blacklight::Document::ThumbnailComponent`.

**Comment by banukutlu** [comment]
> @banukutlu - this should be ready for review!
> 
> @awead helped me clean this up this afternoon. The thumbnail is now linking properly on the index view now that we are using the `Blacklight::Document::ThumbnailComponent`.

yes! I liked how it works right now, thanks so much. I had this already reviewed, just after a quick glance I will merge it 👍

**Comment by banukutlu** [comment]
just to note, we will need to make some changes to external_links class since with https://github.com/psu-libraries/psulib_traject/issues/277 we will now have better labels to these links, but I am merging this PR now since it has been open for a while and it has already good amount of changes and works as is without the better labels. We can handle those labels in another PR. thanks so much @nicktiberi 👌  🎉

**Review by banukutlu — APPROVED** [review]

**Pull request merged**
