### PR TITLE
add announcement messages to readonly file

### PR DESCRIPTION
**Pull request by banukutlu**

### CODE REVIEW

**Comment by banukutlu** [comment]
> Let me know what you think of #508

It was 👌, I got that one merged into this branch. Thanks @cdmo!

**Comment by cdmo** [comment]
https://github.com/psu-libraries/psulib_blacklight/pull/510 ?

**Comment by banukutlu** [comment]
> #510 ?

looked great, it is merged in, thanks!

**Comment by cdmo** [comment]
changing this to the 3x milestone

**Pull request merged**
