### PR TITLE
Adds scan_sim, the special collections accessioning number, to search…

### PR DESCRIPTION
**Pull request by cdmo**
… algorithm

Requires https://github.com/psu-libraries/psulib_traject/pull/247

Not that this adds `scan_sim` to the Identifiers Advanced Search field too

### CODE REVIEW

**Comment by cdmo** [comment]
Once psu-libraries/psulib_traject#247 is merged and deployed to QA, and once QA has been reindexed to include this new field, I'd like to deploy this feature branch to QA and do some tests on a full index _before merging_

**Comment by banukutlu** [comment]
@cdmo This looks good to me but do you wanna test it on QA before marking it for review?

**Comment by cdmo** [comment]
I guess it's ok to merge 🤷 

I think I was just thinking it's something that's hard to test and do dev on without a full nearly 8 million record index to work with. But does seem to me that this is fine the way it is. If you're good with it I am.

**Review by banukutlu — APPROVED** [review]
I think it looks good 👍

**Pull request merged**
