### PR TITLE
switch to read only 

### PR DESCRIPTION
**Pull request by Smullz622**
for symphony saas migration, hides I want it button

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
This can be done dynamically through `config` by setting the `SETTINGS__readonly` environment variable to true and restarting the deployment. We may want to do this instead of cutting a release for each config change.

**Comment by Smullz622** [comment]
@whereismyjetpack that would be done [here](https://github.com/psu-libraries/catalog-config/blob/d8bc9ac76e53d044fa4d0f0e6b23227212ce8716/clusters/prod/manifests/psulib_blacklight/prod.yaml#L55) correct, similar to `hide_annoucement`

**Comment by whereismyjetpack** [comment]
Yup. you could do it there, too!

**Comment by Smullz622** [comment]
doing this in config instead

**Pull request closed without merging**
