### PR TITLE
bundler 2 upgrade

### PR DESCRIPTION
**Pull request by banukutlu**
Issue #365

### CODE REVIEW

**Comment by banukutlu** [comment]
> Do you want to change the name of this PR to prefix it with "WIP: "? I assume that you don't want a review yet...

I got it to work so I removed the WIP prefix, only concern as we talked earlier be if this change affect deployments script much?

**Comment by cdmo** [comment]
Yeah, it does affect deployment script, see `install-app.yml` file there. So that task needs updating. I wonder, do we have to remove Bundler 1?

**Comment by banukutlu** [comment]
> install-app.yml

yes OK I just saw the task where it installs the bundler, so that needs to be updated. But I am not sure if we need to remove Bundler 1. We will try it in QA first, but still this PR can wait, there is no rush.

**Comment by cdmo** [comment]
Good. I'd like to take care of some of the bigger outstanding issues left in 0.2.x before we start experimenting if that's alright with you.

**Comment by banukutlu** [comment]
> Good. I'd like to take care of some of the bigger outstanding issues left in 0.2.x before we start experimenting if that's alright with you.

yes, agreed. This can totally wait 👍

**Comment by cdmo** [comment]
Just wanted to say that I tried this locally and it worked fine, we just need a PR into our deploy script to make adjustments there. If that's something you want me to tackle, I'm happy to, just want to get rid of any ambiguity on how to proceed with this. LMK.

**Comment by banukutlu** [comment]
> Just wanted to say that I tried this locally and it worked fine, we just need a PR into our deploy script to make adjustments there. If that's something you want me to tackle, I'm happy to, just want to get rid of any ambiguity on how to proceed with this. LMK.

yes pls, this sounds good to me. again there is no rush pushing this so let's do it if/when we feel comfortable to make changes to our deployment considering with other things we have currently..

**Pull request merged**
