### PR TITLE
removing author sort #288

### PR DESCRIPTION
**Pull request by banukutlu**
Connected to #288

### CODE REVIEW

**Comment by banukutlu** [comment]
> Do we need the `author_ssort` at all anymore then? If not, can you put a connected PR into psulib_traject to remove it there too?

already added ;)

**Comment by cdmo** [comment]
Ok ok guess I should have checked!

**Comment by banukutlu** [comment]
> Ok ok guess I should have checked!

I should have mentioned in the description :)

**Comment by cdmo** [comment]
Totally. Very unprofessional Banu. 😒

**Comment by banukutlu** [comment]
> Totally. Very unprofessional Banu. 😒

😮  😆

**Pull request merged**
