### PR TITLE
return plain text when format is not html

### LINKED ISSUE #1010: render all 404
Presently, we only render 404 for `handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]` -- when a request comes in for something else, like `ids.txt` we throw a template error instead of a 404

### PR DESCRIPTION
**Pull request by whereismyjetpack**
When a user navigates to a non html path, previously the application would throw a 500 template not found error, instead of a 404. for non html requests, we fall back to rendering plain text, with status of 404. 

Fixes #1010

### CODE REVIEW

**Review by banukutlu — APPROVED** [review]
LGTM 👍🏻  thanks @whereismyjetpack 🍻

**Comment by banukutlu** [comment]
just find out that we actually have specs for this one, I totally forgot about it, it is a request spec here https://github.com/psu-libraries/psulib_blacklight/blob/main/spec/requests/errors_spec.rb

**Comment by whereismyjetpack** [comment]
writing up a spec shouldn't be too hard...

_3 days later_

**Comment by whereismyjetpack** [comment]
I've added a request spec to ensure this behavior persists.

**Review by banukutlu — APPROVED** [review]
looks great to me, thanks @whereismyjetpack!

**Pull request merged**
