### PR TITLE
Bound with

### PR DESCRIPTION
**Pull request by cdmo**
tied to https://github.com/psu-libraries/psulib_traject/pull/65

### CODE REVIEW

**Comment by cdmo** [comment]
I'll write a test for the helper 😅

**Comment by banukutlu** [comment]
@cdmo just wanted to make sure if this page https://github.com/psu-libraries/psulib_blacklight/wiki/Exporting-and-Displaying-Bound-With-in-Linked-Notes contains your latest work? Binding Notes field to be added right?

**Comment by cdmo** [comment]
I'll update that wiki too if need be. I'll double check.

**Comment by cdmo** [comment]
I added a test and just stubbed the data I needed that the method expects. I'd like to hear your feedback.

**Comment by cdmo** [comment]
I updated the wiki to add some clarity/specificity.

However, we are not indexing this field beyond the `all_text_tsiv` fields as far as I know and this is on purpose. Can I change the wiki to reflect this or do we need to add an `i` to the dynamic field? @banukutlu

**Comment by cdmo** [comment]
Updated the wiki to clarify the indexing of bound with.

**Comment by cdmo** [comment]
I don't get what Coveralls is so mad about, https://coveralls.io/builds/20600061, I didn't even touch anything in `/models` 🤷‍♂️

**Pull request merged**
