### PR TITLE
updating checked out label and adding it to request_via_ill list

### PR DESCRIPTION
**Pull request by banukutlu**
Issue #632

### CODE REVIEW

**Comment by banukutlu** [comment]
waiting on the new ILL form url for RESERVE-EG and RESERVE-EM locations

**Comment by cdmo** [comment]
I just now noticed that travis is on our old version of ruby, so updated. Build was failing anyway so don't think you would mind.

**Comment by banukutlu** [comment]
> I just now noticed that travis is on our old version of ruby, so updated. Build was failing anyway so don't think you would mind.

sure of course not 👌

**Comment by cdmo** [comment]
I checked the [3 listed here](https://github.com/psu-libraries/psulib_blacklight/issues/632#issuecomment-679334721) and they are not in the local index. Are there examples of this locally?

**Comment by banukutlu** [comment]
> I checked the [3 listed here](https://github.com/psu-libraries/psulib_blacklight/issues/632#issuecomment-679334721) and they are not in the local index. Are there examples of this locally?

yes, examples from our local sample `22080733` and `24053587`

**Pull request merged**
