### PR TITLE
Fully de-sprockets the application. Also, removes ActionCable and Act…

### PR DESCRIPTION
**Pull request by cdmo**
…iveJob which are not needed.

Will fail because blacklight_range_limit modifies `assets`. See https://github.com/projectblacklight/blacklight_range_limit/pull/159

### CODE REVIEW

**Comment by banukutlu** [comment]
@cdmo I have reviewed this, the code changes are all good but I guess we are waiting on PR on the blacklight_range_limit repo? I haven't merged it because of that yet.

**Comment by cdmo** [comment]
yup, converted to draft

**Comment by cdmo** [comment]
Now that blacklight_range_limit has been made safe to use in a no-sprockets world, this is okay to merge (after review of course). There are failing specs that I'm not sure how to resolve because I don't think it can be resolved without mocking.

**Comment by cdmo** [comment]
Also note that the Gemfile.lock still has sprockets because Rails requires it. However it is not loaded into the application anymore.

**Pull request merged**
