### PR TITLE
Update Absorbs fields labels

### PR DESCRIPTION
**Pull request by ruthtillman**
Pretty simple typo fix in catalog controller. Neither label nor field appears to be referred to directly in spec so nothing to change there?

### CODE REVIEW

**Comment by awead** [comment]
Is there a test to see if the referenced solr fields are showing up in the record display  somewhere?

**Comment by ruthtillman** [comment]
catkey 34332311 is one I know has them.

**Comment by banukutlu** [comment]
> Is there a test to see if the referenced solr fields are showing up in the record display somewhere?

I do not think so, we were only adding specs for the customization we added. Since there are many fields that just uses out of the box `config.add_show_field`, we did not add specs for them. There is one for the helper method title_links but it does not specifically checks for this field.

**Review by banukutlu — APPROVED** [review]

**Comment by awead** [comment]
@banukutlu My only concern is that if these lines get remove/changed, then no tests would break. Does that mean we'd be introducing a regression bug?

**Comment by banukutlu** [comment]
> @banukutlu My only concern is that if these lines get remove/changed, then no tests would break. Does that mean we'd be introducing a regression bug?

correct, no tests covers that, we can consider adding specs. there were many straight forward fields like this so we were not sure about the worth of adding them with thinking if somebody is deleting them mistakenly, hopefully the reviewer would catch on that.

**Comment by ruthtillman** [comment]
Yeah there are a ton of these small fields. It would definitely be something the reviewer should catch. Also people will _let me know_ 😹 

I support writing specs but that might need to happen a little later so we can get a thorough coverage expectation because there are many of these little fields.

**Comment by awead** [comment]
@ruthtillman If you want, go ahead and put in a ticket and describes what we need to test. I could be something as simple as testing the Blacklight configuration, or testing the contents of `SolrDocument` or a specific Solr query.

**Comment by banukutlu** [comment]
> 34332311

@ruthtillman this catkey does not exist anymore, could you find another one to check?

**Comment by ruthtillman** [comment]
yeah here we go https://catalog.libraries.psu.edu/catalog/34674450 (typo resplendent)

**Comment by ruthtillman** [comment]
QAd, so ready to go!

**Pull request merged**
