### PR TITLE
Availability: Update View More to show more items in pages of 100

### LINKED ISSUE #504: Long loading availability holdings when clicked View More of a location with many holdings
https://catalog.libraries.psu.edu/catalog/71224 - failing

https://catalog.libraries.psu.edu/catalog/189479 - big but does work, but maybe we could use this to help benchmark?

(also on the My Account side -- how do these behave on loading there? options for improving that? - would need to then be my acct ticket)

### PR DESCRIPTION
**Pull request by nicktiberi**
Closes #504.

Some items have lots of holdings which can cause the browser to lag or sometimes even crash when it attempts to expand thousands of table rows at once.

In particular, the New York Times is bombing in production. Here it is in the preview branch: https://catalog-view-more.dev.k8s.libraries.psu.edu/catalog/71224

### CODE REVIEW

**Review by ajkiessl — APPROVED** [review]
This all looks good to me.  I'll be honest, I'm not sure what all is going on in some of this, but I tested it out on the preview branch and it works nicely.

**Comment by nicktiberi** [comment]
Code Climate is complaining about a decrease in test coverage on [app/controllers/concerns/search_context.rb](https://codeclimate.com/github/psu-libraries/psulib_blacklight/app/controllers/concerns/search_context.rb?to_sha=f946a27d73a8d680a3fa3ce34ef7f6f343271bb3), but I'm not really sure why... 🤔

**Comment by banukutlu** [comment]
> Code Climate is complaining about a decrease in test coverage on [app/controllers/concerns/search_context.rb](https://codeclimate.com/github/psu-libraries/psulib_blacklight/app/controllers/concerns/search_context.rb?to_sha=f946a27d73a8d680a3fa3ce34ef7f6f343271bb3), but I'm not really sure why... 🤔

It is odd that it is showing a decrease because it looks like the same lines are covered between the main and this branch for that file: https://codeclimate.com/github/psu-libraries/psulib_blacklight/app/controllers/concerns/search_context.rb/source?to_sha=f946a27d73a8d680a3fa3ce34ef7f6f343271bb3 and https://codeclimate.com/github/psu-libraries/psulib_blacklight/app/controllers/concerns/search_context.rb/source?to_sha=a15d5d12975daa5c17a07cd48a94142afb3ac5e8

**Review by banukutlu — DISMISSED** [review]
great improvement, thanks @nicktiberi!

**Comment by banukutlu** [comment]
> This all looks good to me. I'll be honest, I'm not sure what all is going on in some of this, but I tested it out on the preview branch and it works nicely.

same here ☝🏻

**Comment by nicktiberi** [comment]
This is ready to go again. The accessibility stuff is kinda hairy, so please let me know if if you have any questions on it.

Code Climate is complaining about some stuff in the new `A11yRow` component, so let me know if you think we should address them. I tried to keep as much of the complexity inside of the `A11yRow` component as possible to avoid bloating the main `Availability` component.

**Comment by nicktiberi** [comment]
In the latest push, I added a few clarifying comments in `A11yRow` and renamed a few state variables to hopefully be more clear.

**Review by ajkiessl — APPROVED** [review]
This all looks good to me.  I can't see exactly what code climate's issue is with the A11yRow stuff, but it looks clean and well written to me.  I'm think it would be fine to leave it as is.

I also tested this with my screen reader.  It sounds good too!

**Comment by nicktiberi** [comment]
> This all looks good to me. I can't see exactly what code climate's issue is with the A11yRow stuff, but it looks clean and well written to me. I think it would be fine to leave it as is.
> 
> I also tested this with my screen reader. It sounds good too!

Thanks for testing this out on screen reader! Glad to know it seems to be working there. 🙏

**Pull request merged**
