### PR TITLE
Myaccount integration

### PR DESCRIPTION
**Pull request by banukutlu**
Issue #505

### CODE REVIEW

**Comment by cdmo** [comment]
Looks good, I think I'd just put the prod url in settings.yml though and remove the production and development files entirely.

**Comment by banukutlu** [comment]
> Looks good, I think I'd just put the prod url in settings.yml though and remove the production and development files entirely.

this is the part, I want to touch base with you actually, the reason why this is still draft. I added those mostly because I was trying to find a way to make sure we do not mistakenly use myaccount prod on our locals. We can override it with a local setting file but still can be missed 🤔   
Also blackcatqa would be using myaccountqa, I guess the deployment script will handle that setting? your thoughts?

**Comment by cdmo** [comment]
I guess I don't feel strong one way or the other. I generally try to avoid specific environment settings so I'd plan to handle this with the ignored settings files locally. We can talk more over zoom orsomething

**Comment by banukutlu** [comment]
> I guess I don't feel strong one way or the other. I generally try to avoid specific environment settings so I'd plan to handle this with the ignored settings files locally. We can talk more over zoom orsomething

sure, let's chat when we can

**Pull request merged**
